# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Cisco


class _Device(_Cisco):
    _type = "device"
    _icon_dir = "resources/cisco/device"


class Access_Gateway(_Device):
    _icon = "access_gateway.png"


class Accesspoint(_Device):
    _icon = "accesspoint.png"


class Ace(_Device):
    _icon = "ace.png"


class Acs(_Device):
    _icon = "acs.png"


class Adm(_Device):
    _icon = "adm.png"


class Androgenous_Person(_Device):
    _icon = "androgenous_person.png"


class Antenna(_Device):
    _icon = "antenna.png"


class Asa_5500(_Device):
    _icon = "asa_5500.png"


class Asic_Processor(_Device):
    _icon = "asic_processor.png"


class Asr_1000_Series(_Device):
    _icon = "asr_1000_series.png"


class Ata(_Device):
    _icon = "ata.png"


class Atm_3800(_Device):
    _icon = "atm_3800.png"


class Atm_Fast_Gigabit_Etherswitch(_Device):
    _icon = "atm_fast_gigabit_etherswitch.png"


class Atm_Router(_Device):
    _icon = "atm_router.png"


class Atm_Switch(_Device):
    _icon = "atm_switch.png"


class Atm_Tag_Switch_Router(_Device):
    _icon = "atm_tag_switch_router.png"


class Avs(_Device):
    _icon = "avs.png"


class Axp(_Device):
    _icon = "axp.png"


class Bbfw(_Device):
    _icon = "bbfw.png"


class Bbfw_Media(_Device):
    _icon = "bbfw_media.png"


class Bbsm(_Device):
    _icon = "bbsm.png"


class Branch_Office(_Device):
    _icon = "branch_office.png"


class Breakout_Box(_Device):
    _icon = "breakout_box.png"


class Bridge(_Device):
    _icon = "bridge.png"


class Broadband_Router(_Device):
    _icon = "broadband_router.png"


class Bts_10200(_Device):
    _icon = "bts_10200.png"


class Ca(_Device):
    _icon = "ca.png"


class Cable_Modem(_Device):
    _icon = "cable_modem.png"


class Callmanager(_Device):
    _icon = "callmanager.png"


class Car(_Device):
    _icon = "car.png"


class Carrier_Routing_System(_Device):
    _icon = "carrier_routing_system.png"


class CddiFddi(_Device):
    _icon = "cddi-fddi.png"


class Cdm(_Device):
    _icon = "cdm.png"


class Cellular_Phone(_Device):
    _icon = "cellular_phone.png"


class Centri_Firewall(_Device):
    _icon = "centri_firewall.png"


class Cisco_Hub(_Device):
    _icon = "cisco_hub.png"


class Ciscosecurity(_Device):
    _icon = "ciscosecurity.png"


class Ciscoworks(_Device):
    _icon = "ciscoworks.png"


class Class_4_5_Switch(_Device):
    _icon = "class_4_5_switch.png"


class Cloud(_Device):
    _icon = "cloud.png"


class Communications_Server(_Device):
    _icon = "communications_server.png"


class Contact_Center(_Device):
    _icon = "contact_center.png"


class Content_Service_Router(_Device):
    _icon = "content_service_router.png"


class Content_Service_Switch_1100(_Device):
    _icon = "content_service_switch_1100.png"


class Content_Switch(_Device):
    _icon = "content_switch.png"


class Content_Switch_Module(_Device):
    _icon = "content_switch_module.png"


class CsMars(_Device):
    _icon = "cs-mars.png"


class CsmS(_Device):
    _icon = "csm-s.png"


class Csu_Dsu(_Device):
    _icon = "csu_dsu.png"


class Cube(_Device):
    _icon = "cube.png"


class Detector(_Device):
    _icon = "detector.png"


class DirectorClass_Fibre_Channel_Director(_Device):
    _icon = "director-class_fibre_channel_director.png"


class Directory_Server(_Device):
    _icon = "directory_server.png"


class Diskette(_Device):
    _icon = "diskette.png"


class Distributed_Director(_Device):
    _icon = "distributed_director.png"


class DotDot(_Device):
    _icon = "dot-dot.png"


class Dpt(_Device):
    _icon = "dpt.png"


class Dslam(_Device):
    _icon = "dslam.png"


class Dual_Mode_Ap(_Device):
    _icon = "dual_mode_ap.png"


class Dwdm_Filter(_Device):
    _icon = "dwdm_filter.png"


class End_Office(_Device):
    _icon = "end_office.png"


class Fax(_Device):
    _icon = "fax.png"


class Fc_Storage(_Device):
    _icon = "fc_storage.png"


class Fddi_Ring(_Device):
    _icon = "fddi_ring.png"


class Fibre_Channel_Disk_Subsystem(_Device):
    _icon = "fibre_channel_disk_subsystem.png"


class Fibre_Channel_Fabric_Switch(_Device):
    _icon = "fibre_channel_fabric_switch.png"


class File_Cabinet(_Device):
    _icon = "file_cabinet.png"


class File_Engine(_Device):
    _icon = "file_engine.png"


class File_Server(_Device):
    _icon = "file_server.png"


class Fileserver(_Device):
    _icon = "fileserver.png"


class Firewall(_Device):
    _icon = "firewall.png"


class Front_End_Processor(_Device):
    _icon = "front_end_processor.png"


class Gatekeeper(_Device):
    _icon = "gatekeeper.png"


class General_Applicance(_Device):
    _icon = "general_applicance.png"


class Generic_Building(_Device):
    _icon = "generic_building.png"


class Generic_Gateway(_Device):
    _icon = "generic_gateway.png"


class Generic_Processor(_Device):
    _icon = "generic_processor.png"


class Generic_Softswitch(_Device):
    _icon = "generic_softswitch.png"


class Gigabit_Switch_Atm_Tag_Router(_Device):
    _icon = "gigabit_switch_atm_tag_router.png"


class Government_Building(_Device):
    _icon = "government_building.png"


class Ground_Terminal(_Device):
    _icon = "ground_terminal.png"


class Guard(_Device):
    _icon = "guard.png"


class H323(_Device):
    _icon = "h323.png"


class Handheld(_Device):
    _icon = "handheld.png"


class Hootphone(_Device):
    _icon = "hootphone.png"


class Host(_Device):
    _icon = "host.png"


class Hp_Mini(_Device):
    _icon = "hp_mini.png"


class Hub(_Device):
    _icon = "hub.png"


class Iad_Router(_Device):
    _icon = "iad_router.png"


class Ibm_Mainframe(_Device):
    _icon = "ibm_mainframe.png"


class Ibm_Mini_As400(_Device):
    _icon = "ibm_mini_as400.png"


class Ibm_Tower(_Device):
    _icon = "ibm_tower.png"


class Icm(_Device):
    _icon = "icm.png"


class Ics(_Device):
    _icon = "ics.png"


class Intelliswitch_Stack(_Device):
    _icon = "intelliswitch_stack.png"


class Internet_Streamer(_Device):
    _icon = "internet_streamer.png"


class Ios_Firewall(_Device):
    _icon = "ios_firewall.png"


class Ios_Slb(_Device):
    _icon = "ios_slb.png"


class Ip(_Device):
    _icon = "ip.png"


class Ip_Communicator(_Device):
    _icon = "ip_communicator.png"


class Ip_Dsl(_Device):
    _icon = "ip_dsl.png"


class Ip_Phone(_Device):
    _icon = "ip_phone.png"


class Ip_Telephony_Router(_Device):
    _icon = "ip_telephony_router.png"


class Iptc(_Device):
    _icon = "iptc.png"


class Iptv_Content_Manager(_Device):
    _icon = "iptv_content_manager.png"


class Iptv_Server(_Device):
    _icon = "iptv_server.png"


class Iscsi_Router(_Device):
    _icon = "iscsi_router.png"


class Isdn_Switch(_Device):
    _icon = "isdn_switch.png"


class Itp(_Device):
    _icon = "itp.png"


class Jbod(_Device):
    _icon = "jbod.png"


class Key(_Device):
    _icon = "key.png"


class Keys(_Device):
    _icon = "keys.png"


class Lan_To_Lan(_Device):
    _icon = "lan_to_lan.png"


class Laptop(_Device):
    _icon = "laptop.png"


class Layer_2_Remote_Switch(_Device):
    _icon = "layer_2_remote_switch.png"


class Layer_3_Switch(_Device):
    _icon = "layer_3_switch.png"


class Lightweight_Ap(_Device):
    _icon = "lightweight_ap.png"


class Localdirector(_Device):
    _icon = "localdirector.png"


class Lock(_Device):
    _icon = "lock.png"


class Longreach_Cpe(_Device):
    _icon = "longreach_cpe.png"


class Mac_Woman(_Device):
    _icon = "mac_woman.png"


class Macintosh(_Device):
    _icon = "macintosh.png"


class Man_Woman(_Device):
    _icon = "man_woman.png"


class Mas_Gateway(_Device):
    _icon = "mas_gateway.png"


class Mau(_Device):
    _icon = "mau.png"


class Mcu(_Device):
    _icon = "mcu.png"


class Mdu(_Device):
    _icon = "mdu.png"


class Me_1100(_Device):
    _icon = "me_1100.png"


class Mediator(_Device):
    _icon = "mediator.png"


class Meetingplace(_Device):
    _icon = "meetingplace.png"


class Mesh_Ap(_Device):
    _icon = "mesh_ap.png"


class Metro_1500(_Device):
    _icon = "metro_1500.png"


class Mgx_8000_Multiservice_Switch(_Device):
    _icon = "mgx_8000_multiservice_switch.png"


class Microphone(_Device):
    _icon = "microphone.png"


class Microwebserver(_Device):
    _icon = "microwebserver.png"


class Mini_Vax(_Device):
    _icon = "mini_vax.png"


class Mobile_Access_Ip_Phone(_Device):
    _icon = "mobile_access_ip_phone.png"


class Mobile_Access_Router(_Device):
    _icon = "mobile_access_router.png"


class Mobile_Streamer(_Device):
    _icon = "mobile_streamer.png"


class Modem(_Device):
    _icon = "modem.png"


class Moh_Server(_Device):
    _icon = "moh_server.png"


class Mse(_Device):
    _icon = "mse.png"


class Mulitswitch_Device(_Device):
    _icon = "mulitswitch_device.png"


class MultiFabric_Server_Switch(_Device):
    _icon = "multi-fabric_server_switch.png"


class Multilayer_Remote_Switch(_Device):
    _icon = "multilayer_remote_switch.png"


class Mux(_Device):
    _icon = "mux.png"


class Mxe(_Device):
    _icon = "mxe.png"


class Nac_Appliance(_Device):
    _icon = "nac_appliance.png"


class Nce(_Device):
    _icon = "nce.png"


class Nce_Router(_Device):
    _icon = "nce_router.png"


class Netflow_Router(_Device):
    _icon = "netflow_router.png"


class Netranger(_Device):
    _icon = "netranger.png"


class Netsonar(_Device):
    _icon = "netsonar.png"


class Network_Management(_Device):
    _icon = "network_management.png"


class Nexus_1000(_Device):
    _icon = "nexus_1000.png"


class Nexus_2000(_Device):
    _icon = "nexus_2000.png"


class Nexus_5000(_Device):
    _icon = "nexus_5000.png"


class Nexus_7000(_Device):
    _icon = "nexus_7000.png"


class Octel(_Device):
    _icon = "octel.png"


class Ons15500(_Device):
    _icon = "ons15500.png"


class Optical_Amplifier(_Device):
    _icon = "optical_amplifier.png"


class Optical_Services_Router(_Device):
    _icon = "optical_services_router.png"


class Optical_Transport(_Device):
    _icon = "optical_transport.png"


class Pad(_Device):
    _icon = "pad.png"


class Pad_X28(_Device):
    _icon = "pad_x28.png"


class Page_Icon(_Device):
    _icon = "page_icon.png"


class Pbx(_Device):
    _icon = "pbx.png"


class Pbx_Switch(_Device):
    _icon = "pbx_switch.png"


class Pc(_Device):
    _icon = "pc.png"


class Pc_Adapter_Card(_Device):
    _icon = "pc_adapter_card.png"


class Pc_Man(_Device):
    _icon = "pc_man.png"


class Pc_Routercard(_Device):
    _icon = "pc_routercard.png"


class Pc_Software(_Device):
    _icon = "pc_software.png"


class Pc_Video(_Device):
    _icon = "pc_video.png"


class Pda(_Device):
    _icon = "pda.png"


class Phone(_Device):
    _icon = "phone.png"


class Phone_Fax(_Device):
    _icon = "phone_fax.png"


class Pix_Firewall(_Device):
    _icon = "pix_firewall.png"


class Pmc(_Device):
    _icon = "pmc.png"


class Printer(_Device):
    _icon = "printer.png"


class Programmable_Switch(_Device):
    _icon = "programmable_switch.png"


class Protocol_Translator(_Device):
    _icon = "protocol_translator.png"


class Pxf(_Device):
    _icon = "pxf.png"


class Radio_Tower(_Device):
    _icon = "radio_tower.png"


class Ratemux(_Device):
    _icon = "ratemux.png"


class Relational_Database(_Device):
    _icon = "relational_database.png"


class Repeater(_Device):
    _icon = "repeater.png"


class Rf_Modem(_Device):
    _icon = "rf_modem.png"


class Route_Switch_Processor(_Device):
    _icon = "route_switch_processor.png"


class Router(_Device):
    _icon = "router.png"


class Router_Firewall(_Device):
    _icon = "router_firewall.png"


class Router_With_Silicon_Switch(_Device):
    _icon = "router_with_silicon_switch.png"


class Routerin_Building(_Device):
    _icon = "routerin_building.png"


class Rpsrps(_Device):
    _icon = "rpsrps.png"


class Running_Man(_Device):
    _icon = "running_man.png"


class Safeharbor_Icon(_Device):
    _icon = "safeharbor_icon.png"


class Sattelite(_Device):
    _icon = "sattelite.png"


class Sattelite_Dish(_Device):
    _icon = "sattelite_dish.png"


class Scanner(_Device):
    _icon = "scanner.png"


class Server_Switch(_Device):
    _icon = "server_switch.png"


class Server_With_Router(_Device):
    _icon = "server_with_router.png"


class Service_Control(_Device):
    _icon = "service_control.png"


class Service_Module(_Device):
    _icon = "service_module.png"


class Service_Router(_Device):
    _icon = "service_router.png"


class Services(_Device):
    _icon = "services.png"


class Set_Top_Box(_Device):
    _icon = "set_top_box.png"


class Simulitlayer_Switch(_Device):
    _icon = "simulitlayer_switch.png"


class Sip_Proxy_Werver(_Device):
    _icon = "sip_proxy_werver.png"


class Sitting_Woman(_Device):
    _icon = "sitting_woman.png"


class Small_Business(_Device):
    _icon = "small_business.png"


class Small_Hub(_Device):
    _icon = "small_hub.png"


class Softphone(_Device):
    _icon = "softphone.png"


class Softswitch_Pgw_Mgc(_Device):
    _icon = "softswitch_pgw_mgc.png"


class Software_Based_Server(_Device):
    _icon = "software_based_server.png"


class Space_Router(_Device):
    _icon = "space_router.png"


class Speaker(_Device):
    _icon = "speaker.png"


class Ssc(_Device):
    _icon = "ssc.png"


class Ssl_Terminator(_Device):
    _icon = "ssl_terminator.png"


class Standard_Host(_Device):
    _icon = "standard_host.png"


class Standing_Man(_Device):
    _icon = "standing_man.png"


class Standing_Woman(_Device):
    _icon = "standing_woman.png"


class Stb(_Device):
    _icon = "stb.png"


class Storage_Router(_Device):
    _icon = "storage_router.png"


class Storage_Server(_Device):
    _icon = "storage_server.png"


class Stp(_Device):
    _icon = "stp.png"


class Streamer(_Device):
    _icon = "streamer.png"


class Sun_Workstation(_Device):
    _icon = "sun_workstation.png"


class Supercomputer(_Device):
    _icon = "supercomputer.png"


class Svx(_Device):
    _icon = "svx.png"


class System_Controller(_Device):
    _icon = "system_controller.png"


class Tablet(_Device):
    _icon = "tablet.png"


class Tape_Array(_Device):
    _icon = "tape_array.png"


class Tdm_Router(_Device):
    _icon = "tdm_router.png"


class Telecommuter_House(_Device):
    _icon = "telecommuter_house.png"


class Telecommuter_House_Pc(_Device):
    _icon = "telecommuter_house_pc.png"


class Telecommuter_Icon(_Device):
    _icon = "telecommuter_icon.png"


class Terminal(_Device):
    _icon = "terminal.png"


class Token(_Device):
    _icon = "token.png"


class Tp_Mcu(_Device):
    _icon = "tp_mcu.png"


class Transpath(_Device):
    _icon = "transpath.png"


class Truck(_Device):
    _icon = "truck.png"


class Turret(_Device):
    _icon = "turret.png"


class Tv(_Device):
    _icon = "tv.png"


class Ubr910(_Device):
    _icon = "ubr910.png"


class Umg_Series(_Device):
    _icon = "umg_series.png"


class Unified_Presence_Server(_Device):
    _icon = "unified_presence_server.png"


class Unity_Server(_Device):
    _icon = "unity_server.png"


class Unityexpress(_Device):
    _icon = "unityexpress.png"


class Universal_Gateway(_Device):
    _icon = "universal_gateway.png"


class University(_Device):
    _icon = "university.png"


class Upc(_Device):
    _icon = "upc.png"


class Ups(_Device):
    _icon = "ups.png"


class Vault(_Device):
    _icon = "vault.png"


class Video_Camera(_Device):
    _icon = "video_camera.png"


class Vip(_Device):
    _icon = "vip.png"


class Virtual_Layer_Switch(_Device):
    _icon = "virtual_layer_switch.png"


class Voice_Atm_Switch(_Device):
    _icon = "voice_atm_switch.png"


class Voice_Commserver(_Device):
    _icon = "voice_commserver.png"


class Voice_Router(_Device):
    _icon = "voice_router.png"


class Voice_Switch(_Device):
    _icon = "voice_switch.png"


class Vpn_Concentrator(_Device):
    _icon = "vpn_concentrator.png"


class Vpn_Gateway(_Device):
    _icon = "vpn_gateway.png"


class Vsd(_Device):
    _icon = "vsd.png"


class Vss(_Device):
    _icon = "vss.png"


class Wae(_Device):
    _icon = "wae.png"


class Wavelength_Router(_Device):
    _icon = "wavelength_router.png"


class Web_Browser(_Device):
    _icon = "web_browser.png"


class Web_Cluster(_Device):
    _icon = "web_cluster.png"


class WiFi_Tag(_Device):
    _icon = "wi-fi_tag.png"


class Wireless(_Device):
    _icon = "wireless.png"


class Wireless_Bridge(_Device):
    _icon = "wireless_bridge.png"


class Wireless_Location_Appliance(_Device):
    _icon = "wireless_location_appliance.png"


class Wireless_Router(_Device):
    _icon = "wireless_router.png"


class Wireless_Transport(_Device):
    _icon = "wireless_transport.png"


class Wism(_Device):
    _icon = "wism.png"


class Wlan_Controller(_Device):
    _icon = "wlan_controller.png"


class Workgroup_Director(_Device):
    _icon = "workgroup_director.png"


class Workgroup_Switch(_Device):
    _icon = "workgroup_switch.png"


class Workstation(_Device):
    _icon = "workstation.png"


class Www_Server(_Device):
    _icon = "www_server.png"


# Aliases
